export enum ErrorCode {
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  CART_NOT_FOUND = 'CART_NOT_FOUND',
  CART_NOT_ACTIVE = 'CART_NOT_ACTIVE',
  CART_ALREADY_CHECKED_OUT = 'CART_ALREADY_CHECKED_OUT',
  CART_EXPIRED = 'CART_EXPIRED',
  INSUFFICIENT_STOCK_FOR_PRODUCT = 'INSUFFICIENT_STOCK_FOR_PRODUCT',
  INVALID_QUANTITY = 'INVALID_QUANTITY',
  PRODUCT_NOT_IN_CART = 'PRODUCT_NOT_IN_CART',
  CHECKOUT_FAILED_INSUFFICIENT_STOCK = 'CHECKOUT_FAILED_INSUFFICIENT_STOCK',
}
